---
 - name: setup nginx web server
   #hosts: localhost
   hosts: awsEC2Instances
   #connection: local   # DOES NOT create a local SSH connection to localhost. It just does what is required directly.
   become: yes
   tags: setup-webserver

   roles:
     - webserver
